### ISSUE TITLE
Please add support for loading unicode .dxf files.

### ISSUE THREAD

**Issue by mcai** [ixmilia/dxf#117]
After reading and writing the same .dxf file, AutoCAD (2018/2019) cannot open the .dxf file possibly due to unrecognized characters (such as ???) in layer names outputted by the lxmilia DXF library. After I've read the library's source code, I find you use ASCII encoding for reading and writing .DXF files. Please support loading and writing unicode .dxf files.

Thanks for your great effort building such a powerful library.

**Comment by brettfo** [comment]
Are you using the NuGet package or building locally to read unicode files?  I only recently fixed reading/writing unicode files in #109, but those changes are only present if you build locally from `master`; they're not in the NuGet package.

If you need to clone/build locally the best way is to use `build-and-test.cmd`/`build-and-test.sh` the first time because there's a tool that generates a lot of code needed to build in Visual Studio.
