### ISSUE TITLE
Feature: dxf to pdf conversion

### ISSUE THREAD

**Issue by nzain** [ixmilia/dxf#119]
One of our customers creates a lot of dxf files through our software + ixmilia.dxf, but needs to automagically _convert_ them to pdf files.

Intriguingly there is also https://github.com/ixmilia/pdf and I was thinking about ways to bring those together. Something like a `IDxfRenderer` interface with PDF as one implementation in a separat package. An implementation would need to

- scale some content (all or custom bbox) to some output (DinA4, Letter, margins, etc.)
- render all entities: sounds like a lot of work, but some entities might easily translate to pdf objects.

To be honest, I think this is too much work. What's your opinion?

For me: points, lines, arcs, polylines, dimensions, text (pdf+encoding=eeeek) would probably suffice and I might try to implement this reduced feature set on my own. But I can't estimate the required effort. My initial web search didn't bring up a smart alternative.

**Comment by brettfo** [comment]
That's a feature I've been considering for some time.  I just created the repo [ixmilia/converters](https://github.com/ixmilia/converters) and added you as a collaborator, so you should have write access.  Currently it's basically empty except for submodule pointers to ixmilia/dxf and ixmilia/pdf.  I went with submodules because it's easier to swap out your own local copy for any changes you have than dealing with converting a `<PackageReference>` into a project or assembly reference.  That and I haven't published a package from ixmilia/pdf yet.

ixmilia/pdf is horribly under-featured and likely incorrect, but the majority of the work in creating a PDF of a DXF file is drawing lines, circles, and arcs, and all of that works.  There is basic support for writing text, but as it stands it's not quite ready.

In another project I've done some simple work like this, but I was using an intermediate format for drawings, not the DXF file directly, but it's still a good starting point.  Look at [this](https://github.com/ixmilia/bcad/blob/master/src/IxMilia.BCad.FileHandlers/Plotting/Pdf).  Note, there is also a simple [SVG](https://github.com/ixmilia/bcad/tree/master/src/IxMilia.BCad.FileHandlers/Plotting/Svg) and [PNG](https://github.com/ixmilia/bcad/tree/master/src/BCad/Plotting/Png) exporter, too, that we may eventually want to bring over.

**Comment by brettfo** [comment]
Also, I certainly didn't create that repo just to make you do all the work; as I get time I fully expect I'll add to it and port the PDF/PNG/SVG converters, but I wanted to make sure you wouldn't be blocked by any inaction on my part.

**Comment by nzain** [comment]
Oh wow. Okay!

Creating a modern open source PDF library will bring a lot of downloads,
tickets, and eventually fame. According to my last research (open source
only) there is a dead outdated project often found in forum threads, one
outdated degenerated project that's still available, and a very small fresh
incomplete implementation inside OxyPlot (not available stand-alone, but we
use OxyPlot anyways). Well, and thousands of expensive 3rd party libs that
promise the sky.

My biggest headache is text encoding. I've read the PDF spec with utf8 or
utf16 in mind, but reality is that you have to embed tables to explain
Unicode inside the PDF.

Regardless, I'm looking forward to work with you and earn some fame :-)

Brett V. Forsgren <notifications@github.com> schrieb am Do., 10. Okt. 2019,
23:14:
