### ISSUE TITLE
Library fails to open AutoCAD dxf file - ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by kub1x** [ixmilia/dxf#159]
Enclosed is a file which fails to Load (added extra .txt extension just to upload to GitHub). Loading throws `System.ArgumentOutOfRangeException` on `DxfCommonConvertor.DateDouble()` somewhere around `AcDbIndex` and `AcDbSpatialIndex`. 

When the file was converted to v2018 using [ODA File Converter](https://www.opendesign.com/guestfiles/oda_file_converter), it loads fine, which makes me think the dxf file might be generated by too new version of AutoCAD (from the dxf file: AC1032 - DWG AutoCAD 2018/2019/2020)? 

[pokus01.dxf.txt](https://github.com/ixmilia/dxf/files/6336883/pokus01.dxf.txt)

**Comment by brettfo** [comment]
Thanks for filing an issue!

AutoCAD 2018+ files (AC1032) are supported, but the issue was a bad handling of the values of a `SPATIAL_INDEX` object; I misinterpreted the spec as saying that there is exactly 1 code `40` value that must be a timestamp, but what I didn't realize is that then multiple code `40` values can follow that AutoDesk doesn't specify the meaning of, but they're obviously not timestamps.  The fix was to place all subsequent code `40` values into a list.

Fixed in commit b7e05f232d6991d673a732e2ef5848b73f00e8c8.
