### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by sampletext32** [ixmilia/dxf#164]
Hey, @brettfo. I've been looking through the code and found some possible optimizations.

Here are a few of them:

- For the `BinaryHelpers` class [link](https://github.com/ixmilia/dxf/blob/main/src/IxMilia.Dxf/BinaryHelpers.cs)
  * `CombineBytes` can be replaced with simple LINQ - `SelectMany(d => d).ToArray()` which is easier to read.
  * `ChunkBytes` has a potential UB - if `data.Length` is not a multiplier of `chunkSize` - the remainder bytes are completely ignored.
  * Also for `ChunkBytes` - if the `data` is null, then it should throw a `NullArgumentException`, instead of returning empty collection.
- For the `DxfCommonConverters` class [link](https://github.com/ixmilia/dxf/blob/main/src/IxMilia.Dxf/DxfCommonConverters.cs)
  * `SplitIntoLines` should not modify string (it's memory expensive), and should use proper `.Substring()` with offset.
  
  There are more optimization which I found. Should I open a PR with them?

**Comment by brettfo** [comment]
- `BinaryHelpers`
  - `CombineBytes` using `SelectMany`; I have no preference.  I'm OK with the existing implementation, but `SelectMany` does simplify the look of it.
  - `data.Length` not being a multiple of `chunkSize` - do you mean the call to `.Take(chunkSize)`?  That method will return up to that number of bytes, but if fewer are available, it just returns what it can, so no undefined behavior there.
  - `data` being `null` - I'd like to retain this behavior.  Due to the various ways the entities and objects can be constructed, it's much easier to return an empty set than to ensure that `data` is never null at the call site.

- `DxfCommonConverters`
  - `SplitIntoLines` - maintaining an offset would certainly reduce allocations, this would be a good improvement.
