### ISSUE TITLE
Why dxf R12 only out save can be open by autocad 

### ISSUE THREAD

**Issue by xiaohelong** [IxMilia/Dxf#77]
Why dxf R12 only out save can be open by autocad

**Comment by brettfo** [comment]
The DXF specification is very loosely (and poorly) defined and many CAD programs, particularly AutoCAD, are very picky about what they can open, but most CAD programs can open minimal R12 files because they are very simple.

Is there a particular drawing you have that AutoCAD is unable to open after editing with this library?  I'd like a copy of it if you can share it.  If you can't share it on GitHub then you can email it to <span>support</span><span>@</span><span>ixmilia.com</span> and I'll ensure it isn't published anywhere.
